docs:
  - changed-files:
      - any-glob-to-any-file: ['docs/**', '**/*.md']
security:
  - changed-files:
      - any-glob-to-any-file: ['security/**']
ci:
  - changed-files:
      - any-glob-to-any-file: ['.github/**']
roadmap:
  - changed-files:
      - any-glob-to-any-file: ['docs/stakeholders/**', 'docs/architecture/**']