name: Roadmap – Create Project (Manual)

on:
  workflow_dispatch:
    inputs:
      title:
        description: "Project title"
        required: true
        default: "MERAJUTASA Strategic Roadmap"
      description:
        description: "Project short description"
        required: true
        default: "High‑level milestones and epics aligned to docs/ROADMAP.md and GOVERNANCE.md; auto‑tracks Issues/PRs via labels (priority:P0/P1/P2, area:*, stakeholder:*)."

permissions:
  contents: read

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Create Projects v2 board under user
        uses: actions/github-script@v7
        env:
          GH_OWNER_LOGIN: wahyumumtazsyah04
          TITLE: ${{ github.event.inputs.title }}
          DESC: ${{ github.event.inputs.description }}
        with:
          github-token: ${{ secrets.PROJECTS_TOKEN }}
          script: |
            const ownerLogin = process.env.GH_OWNER_LOGIN;
            const title = process.env.TITLE;
            const desc = process.env.DESC;

            const q1 = `
              query($login:String!) {
                user(login: $login) { id url login }
              }`;
            const r1 = await github.graphql(q1, { login: ownerLogin });
            if (!r1?.user?.id) {
              core.setFailed(`User not found: ${ownerLogin}`);
            }
            const ownerId = r1.user.id;

            const m1 = `
              mutation($ownerId:ID!, $title:String!, $desc:String) {
                createProjectV2(input:{ ownerId:$ownerId, title:$title, shortDescription:$desc }) {
                  projectV2 { id title url number }
                }
              }`;
            const r2 = await github.graphql(m1, { ownerId, title, desc });

            const project = r2.createProjectV2.projectV2;
            core.notice(`Created Project: ${project.title} → ${project.url}`);
            core.setOutput("project_url", project.url);
            core.setOutput("project_number", project.number);
            core.notice(`Next: set MERAJUTASA_ROADMAP_URL repo variable to: ${project.url}`);